server:
  port: 7002
spring:
  application:
    name: modding-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zwOrion/modding
          search-paths: modding-config/config-server
          default-label: master
